# -*- coding: utf-8 -*-
"""vector_store.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10ZXSkJ0-TZON3ESB6fg38-gQpWWKwKr4
"""

from langchain.vectorstores import Chroma
from langchain.embeddings import OpenAIEmbeddings

def init_vector_db():
    embedding = OpenAIEmbeddings()
    return Chroma(embedding_function=embedding)