# -*- coding: utf-8 -*-
"""groq_wrapper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GWQQx-img9SZqEeM0PcFxXx9tCnVqR2j
"""

from langchain_groq import ChatGroq
from config import GROQ_API_KEY

def load_groq_llm():
    return ChatGroq(
        model="llama-3-8b-instruct",
        temperature=0.3,
        groq_api_key=GROQ_API_KEY
    )
